download:
	curl -L https://cdn.jsdelivr.net/npm/onnxruntime-web@1.20.1/dist/ort.min.mjs > ort.min.mjs
	curl -L https://cdn.jsdelivr.net/npm/onnxruntime-web@1.20.1/dist/ort-wasm-simd-threaded.mjs > ort-wasm-simd-threaded.mjs
	curl -L https://cdn.jsdelivr.net/npm/onnxruntime-web@1.20.1/dist/ort-wasm-simd-threaded.wasm > ort-wasm-simd-threaded.wasm
	curl -L https://huggingface.co/DjB314/RapidOCR/resolve/main/v3.9.2/onnx/PP-OCRv6/rec/PP-OCRv6_rec_small.onnx > PP-OCRv6_rec_small.onnx